### ISSUE TITLE
Make Android part of repo fork friendly

### ISSUE THREAD

**Issue by aaronjwood** [urbandroid-team/Sleep-as-Android-Garmin-Addon#11]
After forking and opening the Android code base in Android Studio there are some errors that devs will hit:

1. [Key doesn't exist](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/blob/master/SleepGarmin-android/app/build.gradle#L41) (can be sidestepped by commenting out the `signingConfigs` section along with [this](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/blob/master/SleepGarmin-android/app/build.gradle#L51))
2. [Library doesn't exist](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/blob/master/SleepGarmin-android/app/build.gradle#L69) (this is where I'm currently at, where can I get this?)

**Comment by Artaud** [comment]
Mkay this is stupid from me, sorry!
1) Yes, please do as you say.

2) This is our internal common library, there is actually just one usage of it which you could comment out ([this line](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/blob/97607b0c299edeac3fc7947a3d08d85e9005d3c7/SleepGarmin-android/app/src/main/java/com/urbandroid/sleep/garmin/SleepAsGarminReceiver.java#L151))
but then your fork wouldn't be able to assemble debug reports in the same way as the original.
So the library is here:
[urbandroidcommon1.5.zip](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/files/2455268/urbandroidcommon1.5.zip)
Unpack it into your local maven repository, so the final path would be ~/.m2/repository/com/urbandroid/common/1.5

**Comment by aaronjwood** [comment]
Awesome, thanks! Can the common lib be open sourced so that people don't need to manually come here and download a zip file?

**Comment by Artaud** [comment]
Added in 0d0d2df7065970cf866646b7df4d9f44d55fe4b3
It's not open sourced really but I included the aar in the project and linked to it in the gradle file, so it's hassle-free now.
Thanks!
