### ISSUE TITLE
App on watch cannot be exited when in a specific state

### ISSUE THREAD

**Issue by Artaud** [urbandroid-team/Sleep-as-Android-Garmin-Addon#12]
Investigate: At some point the watch app will be stuck in "Stopping" state with no option to actually exit the app

**Comment by MrFly** [comment]
Noticed the same here with VA3. Sometimes I'm even not able to scroll, sometimes the screen keeps scrollable. I tried a bit (was able to open the shortcut menu) and noticed, that after "Stopping" was shown up, I was able to long press on the screen. After a time the "! CIQ" logo was shown and then I was able to use the "back" gesture to get back to the clock widget. Maybe this was a random behaviour, but I will try it next time it hangs...

**Comment by aaronjwood** [comment]
Is this for https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/issues/4?

**Comment by MrFly** [comment]
No. :-)

**Comment by gcupic** [comment]
I can confirm the bug on Garmin Fenix 3hr combined with OnePlus 6 both running on fresh SW packages

**Comment by Artaud** [comment]
This is impossible to fix properly without a fix on the Garmin side (see https://forums.garmin.com/forum/developers/connect-iq/connect-iq-bug-reports/158068- )
I have pushed a workaround in b41852e9cb4066051d561ff737cfdefae36207f3

**Comment by gcupic** [comment]
> This is impossible to fix without a fix on the Garmin side (see https://forums.garmin.com/forum/developers/connect-iq/connect-iq-bug-reports/158068- )
> I have pushed a workaround in [b41852e](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/commit/b41852e9cb4066051d561ff737cfdefae36207f3)

Hi,

will it be published in the Garmin Connect Store or we would need to sideload it somehow? 

Thanks!

**Comment by Artaud** [comment]
I will publish it today or tomorrow.

**Comment by nmmacmillan** [comment]
:( picked up a VA4 today and I'm seeing this too. Anything I can do?

**Comment by gbossss** [comment]
Same here with VA4... Only workaround for me is to restart the watch...
