### ISSUE TITLE
UnexpectedTypeException in onTap crash

### ISSUE THREAD

**Issue by Artaud** [urbandroid-team/Sleep-as-Android-Garmin-Addon#13]
Thanks to @MrFly, we've got a bug to squash .]

---
Error: Unhandled Exception
Time: 2018-10-16T19:38:28Z
Part-Number: 006-B2700-00
Firmware-Version: '5.40'
Language-Code: deu
ConnectIQ-Version: 3.0.3
Filename: 201809~1
Appname: Sleep
Message: 'UnexpectedTypeException: Expected Number/Float/Long/Double, given null/Float'
Stack:
  - pc: 0x1000276c
    File: '/home/artaud/prog/urbandroid/source/SleepGarmin/SleepGarmin-watch/source/SleepMainDelegate.mc'
    Line: 55
    Function: onTap
  - pc: 0x30001d0d
```

_Originally posted by @MrFly in https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/issues/10#issuecomment-430877353_

**Comment by MrFly** [comment]
Great :-) Hope I'll find some more :-D

**Comment by Artaud** [comment]
Fixed in https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/commit/e8331532f075744a9a5a5c79b6d2ce3dbccd3c69
