### ISSUE TITLE
List of issues on Forerunner 935

### ISSUE THREAD

**Issue by adarazs** [urbandroid-team/Sleep-as-Android-Garmin-Addon#21]
I don't want to spam the issue tracker with too many FR935 related issues, so I'm making this one for the ones I noticed.

Versions (all of them the latest stable releases, as far as I know):

Connect IQ App: 20181128
Android App: 20181011
Sleep Garmin: 20181206
"Sleep tracking from watch" app: 1.0
Garmin Forerunner 935 firmware: 11.00

This current setup is actually rock solid and tracks my sleeps without ever restarting the watch/disconnecting/etc.  The battery drain is not bad either though the FR935 has a huge battery (it's using about 1-2%/hour). The previous release had a lot of stability problems, but they seem to be fixed, kudos! Also kudos for the open source approach!

However there are regressions that new release introduced, which are possible to work around, but definitely result in a poor user experience until you figure out the only right combination to start/stop tracking. Here's a list:

1. After starting the Sleep app on the watch, the text is stuck on "Starting..." instead of "Tracking" (this was working properly in the previous version of the Connect IQ app) -- it still tracks though
2. Cannot start tracking from the main Android app, have to start it through the watch, otherwise it's stuck at "Waiting for connectivity..." until it times out without popping up the "Start Sleep?" question on the watch
3. Cannot stop tracking on the phone, have to select "Stop tracking" on the watch app, otherwise tracking will restart on the Android app after a short while
4. The design of the Connect IQ screen is very clumsy on the circular screen, the previous/next options are barely visible/cut off on the top/bottom of the screen, they should be a bit lower to make them visible
5. there are also no backgrounds to anything on the Connect IQ app, just a black background with a few lines of white text -- I see from this project's source that other watch versions have nice backgrounds, it should work on the FR935 as well, it's pretty much the same hardware as the Fenix 5/5s, screen size for sure

I'm on the stable SaA Android app, not using heart rate tracking function (because it's not in the stable yet). The Forerunner 935 is a very popular device (especially for triathlonists), so it would be cool to have stable and good looking app on it, not just for my own sake. Let me know if I can help by testing some fixes.

Once again, thanks for all the work on this project (and on Sleep as Android in general), it's very much appreciated!

**Comment by Artaud** [comment]
Big thanks for listing all the issues specific for this watch! (and of course for all the kudos!)

Issues:
1. Okay this needs a fix, doesn't seem to me to be related to the underlying Garmin bug
2. Strange. Will take a look at it. Maybe related to the context wrapper I introduced to try to deal with a non-critical bug in the Garmin SDK (which is different from the big comm bug)
3. Seems to be related to the big garmin comm bug
4. Good point, will fix
5. There are actually no backgrounds on any platform. There were some some time ago but I removed them, because there were so many unexplainable crashes that I just blindly wanted to use as low memory as possible in order to mitigate random low memory issues.

**Comment by adarazs** [comment]
Hey @Artaud, thanks for answering. I have good news. Version 20181212 of the Android app just turned up on my Play Store and it seems that issue 1), 2) and 3) are fixed. (I played with it for 10 minutes, starting and stopping tracking all the possible ways, all worked.) The previous stable was quite old, but I didn't expect that the issue would be solved on the Android app side.

I understand the reason for removing the backgrounds. I agree it's better to keep the app bare-bone if it improves reliability.

As there's only issue 4) remaining here, I'll close this one. Feel free to reopen it if you want to track 4) by this, but probably it's better to do it separately.

Best regards,
Attila
