### ISSUE TITLE
The sleep app on Garmin vivoactive 3 cannot be closed on the watch.

### ISSUE THREAD

**Issue by Artaud** [urbandroid-team/Sleep-as-Android-Garmin-Addon#22]
https://secure.helpscout.net/conversation/918396512/86661?folderId=222992

**Comment by CWempe** [comment]
This might also be a duplicate of #4.

I cannot not the the content of the linked website.

Maybe this issue should be closed if we do not have any detail.

**Comment by Artaud** [comment]
Yes, this regards only the legacy version of the app. However I've noticed there's an issue with closing the app from the watch as well, so I'm investigating.
