### ISSUE TITLE
Don't trigger Backlight on movement/gesture (Fenix 6 / Power Profiles)

### ISSUE THREAD

**Issue by futureweb** [urbandroid-team/Sleep-as-Android-Garmin-Addon#24]
Hey there,
it's really annoying when the Backlight always triggers when moving around a bit in bed (already woke up because of this) ..., but as I rely on "Gesture Backlist activation" on running and other activities I can't disable it (as advised here: https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/issues/9)
On newer Fenix Models like the Fenix 6 one can configure Power Profiles, and those Power Profiles can be activated within Activity Settings. So it would be possible to create a Power Profile with disabled Backlight which one could assign to "Sleep App" ...
Mind implementing this Feature? ;-)
thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by Artaud** [comment]
Hello! 
Are you talking about the "Power modes" of Power manager? I could find this in the Garmin docs https://support.garmin.com/en-US/?faq=UKdcLjyUEZ4xdiX5HWzgp7
But at a quick glance it seems to me that the power profiles/modes are only user-configurable and I cannot add them as a developer. 

Do you have any more information about that?

**Comment by Artaud** [comment]
This should be configurable in system settings, by turning off gesture backlight "during activities".
