### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by chakaponden** [urbandroid-team/Sleep-as-Android-Garmin-Addon#27]
`FAILURE: Build failed with an exception.
 What went wrong:
Execution failed for task :app:mergeDebugResources.
> Could not resolve all files for configuration :app:debugRuntimeClasspath.
   > Could not find com.urbandroid:common:1.23.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/urbandroid/common/1.23/common-1.23.pom
       - https://jcenter.bintray.com/com/urbandroid/common/1.23/common-1.23.aar
       - https://dl.google.com/dl/android/maven2/com/urbandroid/common/1.23/common-1.23.pom
       - https://dl.google.com/dl/android/maven2/com/urbandroid/common/1.23/common-1.23.aar
       - file:/home/chakaponden/.m2/repository/com/urbandroid/common/1.23/common-1.23.pom
       - file:/home/chakaponden/.m2/repository/com/urbandroid/common/1.23/common-1.23.aar
       - https://repo.maven.apache.org/maven2/com/urbandroid/common/1.23/common-1.23.pom
       - https://repo.maven.apache.org/maven2/com/urbandroid/common/1.23/common-1.23.aar
       - file:/home/chakaponden/Sleep-as-Android-Garmin-Addon/SleepGarmin-android/app/libs/common-1.23.aar
       - file:/home/chakaponden/Sleep-as-Android-Garmin-Addon/SleepGarmin-android/app/libs/common.aar
     Required by:
         project :app`

Latest Android Studio 3.6.3

**Comment by Artaud** [comment]
Right, you need the urbandroid common library. You can find it here: 
[1.23.zip](https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/files/4645199/1.23.zip)
Unzip it to ~/.m2/repository/com/urbandroid/common if on Linux. No idea where to put it on other systems.

**Comment by chakaponden** [comment]
But if I change **com.urbandroid:common:1.23** to **com.urbandroid:common:1.14** in build.gradle, everything builds fine.
Looks like com.urbandroid:common:1.23 has to be somewhere in remote repositories and it is missed there, only com.urbandroid:common:1.14 is available

**Comment by Artaud** [comment]
You're right, sorry, I forgot that I included  the lib v14 with this repo (see https://github.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/tree/master/SleepGarmin-android/app/libs). If you put the aar extracted from the attached zip in the same folder, everything should work fine as well.
There shouldn't be really any serious changes between 1.14 and 1.23 that would regard this addon so I believe you're safe with 1.14 if you want to build your version of the addon.

The lib is actually only used for error reporting to us so it doesn't really matter which version you use.
