### ISSUE TITLE
Additional device support

### ISSUE THREAD

**Issue by unizune** [urbandroid-team/Sleep-as-Android-Garmin-Addon#34]
Hello. I am a user using garmin mk1.
I would like to ask for your support for mk1.

Thank you

**Comment by petrnalevka** [comment]
Hello @unizune .. what issues are you having? I think mk1 is a Garmin device so this should IMHO work?

**Comment by Artaud** [comment]
@unizune sorry about that, your Garmin watch is unfortunately no longer supported by the Sleep ConnectIQ app (as it now depends on features not present on your watch), but we have published the old app for download at https://sleep.urbandroid.org/wp-content/uploads/release/Garmin-legacy-watch-app.zip so you can install it from there, just by putting the correct .PRG file onto your watch, in /GARMIN/APPS.
