### ISSUE TITLE
Add new Garmin models

### ISSUE THREAD

**Issue by PaulSD** [urbandroid-team/Sleep-as-Android-Garmin-Addon#36]
Garmin recently released a few new models with new product IDs, including `venusq2` and `venusq2m`:
https://developer.garmin.com/connect-iq/reference-guides/devices-reference/#venu%C2%AEsq2

Could someone update the watch app manifest with the new product IDs and roll a release?

Thanks!

**Comment by Artaud** [comment]
Thanks a lot, merging!

**Comment by Artaud** [comment]
And it's published.
