### ISSUE TITLE
High Battery Consumption and Connection Issues with Garmin Addon - Suggestion to Explore Companion SDK

### ISSUE THREAD

**Issue by encodedLife** [urbandroid-team/Sleep-as-Android-Garmin-Addon#41]
Hello Sleep as Android team,

I am an avid user of your main app and appreciate the functionalities it offers. However, I've been experiencing issues with the Garmin addon. The battery drain that occurs while using it is significant, which prevents me from making full use of this extension.

I've also noted that you acknowledged connection stability issues in your Google Play Store description, which has been a concern as well. This combination of high battery usage and unstable connections certainly impacts the overall user experience.

Recently, I was browsing the Garmin Developer site and stumbled upon something called the "Companion SDK". This software development kit supposedly allows for live broadcasting of various data types.

Have you considered looking into this Companion SDK as a possible solution? It might offer a more efficient way of handling data and could potentially address the aforementioned issues with the Garmin addon.

Link to Companion SDK
https://developer.garmin.com/health-sdk/overview/

**Comment by Artaud** [comment]
Hello, thanks for the tip. We have already talked with Garmin about this Companion SDK and while it probably would solve the issues, they ask an outrageous sum for access to the SDK - either 5000 USD up front, or a vow to purchase a certain quantity of Garmin watches. So we decided not to go with it.

**Comment by encodedLife** [comment]
Hello,

I understand. Thank you for your reply. This is really a shame for Garmin. 
br

**Comment by encodedLife** [comment]
Hello,

I understand. Thank you for your reply. This is really a shame for Garmin. 
br
