### ISSUE TITLE
Testing the Sensor causes an exception on the watch

### ISSUE THREAD

**Issue by wsidl** [urbandroid-team/Sleep-as-Android-Garmin-Addon#7]
**Details**
Device: Vivoactive HR+ (SW version 4.40)
Sleep version: 20180613
Sleep Garmin version: 20170725
Garmin Connect IQ app version: 20170103-upd5

**Symptom**
I had just installed the app add-ons and app onto my watch today and once I had it all set up and connected, ran the "Test Sensors" in the Sleep app. The watch buzzed with the prompt "Launch Sleep (Yes/No)". I tap "Yes" and the Connect IQ Error screen pops up (black screen, stylized "IQ" in the middle with a red circle and exclamation mark). After a few seconds, a slightly different "Launch Sleep" menu appears. Cycle repeats ad-nauseum.

I would provide a stacktrace or something, but nothing no additional files related to the app exists.

**Comment by Artaud** [comment]
Thanks for the feedback. Yes unfortunately there is no debug logging possible on Garmin in production. We're having a thorough debugging session of the Garmin integration in July so hopefully we can find out what is wrong in there.
The main issue is that for some Garmin devices it works splendidly, for other it crashes horridly. Even among the same model.

**Comment by urbandroid-team** [comment]
Is this still an issue with the latest version?

**Comment by wsidl** [comment]
After the last comment, I removed all of the components and haven't tried. Just reloaded everything yesterday and gave it a try. Looks promising!

I'll play with it for the next few days and update this thread.

**Comment by wsidl** [comment]
I would say this is resolved. Have tried it for 3 days and initiating it several different ways and getting good results.
