### ISSUE TITLE
Watch backlight turns on after a few seconds of movement

### ISSUE THREAD

**Issue by aaronjwood** [urbandroid-team/Sleep-as-Android-Garmin-Addon#9]
I'm not sure if this is intended or not but for the Fenix 5 the backlight will come on after some movement. I think this should be made into a setting because some people may not want it to wake the person next to them. It'd also be a good battery saver for people that move around a lot at night.

**Comment by mbirth** [comment]
Got that, too, on a Fenix 5 Plus.

**Comment by Artaud** [comment]
Sorry, closed by mistake.

I believe there is nothing in the API that could prevent this behaviour, or am I mistaken?
I can switch off the backlight with Attention.backlight(off), but that won't change the system behaviour. I guess it could be put into a timer, but then there would be no way to actually activate the backlight if you wanted to.
Any ideas?

**Comment by aaronjwood** [comment]
Hmm, do you know why this behavior doesn't happen with the normal tracking activities? E.g. I start a run and when I'm running the backlight doesn't come on every time my arm moves back and forth. I assumed there was something specific to this app that turns the light on when movement is detected.

**Comment by Artaud** [comment]
I can't test this unfortunately as I have only a Vivoactive at hand. But a good test would be to try any other ConnectIQ app beside the preinstalled ones (i.e. not the normal tracking activities) and check if they do that as well on the Fenix 5.
Could you please try that @aaronjwood or @mbirth ? Thanks a lot...

**Comment by MrFly** [comment]
Noticed the same on VA3 on movements. This is the same behaviour on other apps: On doing the "look on the watch" gesture, the backlight turns on. Are you able to consume this event in a way?

**Comment by aaronjwood** [comment]
I wonder if we could hook the [onExitSleep](https://developer.garmin.com/downloads/connect-iq/monkey-c/doc/Toybox/WatchUi/WatchFace.html#onExitSleep-instance_method) event and [turn off the light](https://developer.garmin.com/downloads/connect-iq/monkey-c/doc/Toybox/Attention.html#backlight-instance_method) in the callback.

**Comment by Artaud** [comment]
I don't think so, that's an event of the WatchFace object, which we don't use at all - and unfortunately cannot use it since we need 100ms period timers, and if used the WatchFace as a View, it only allows for 1minute period timers (or maybe no timers at all? the docs aren't so clear on this)

**Comment by MrFly** [comment]
Maybe it's possible to dim it a bit? It's ok for me, if the light goes on, but a bit darker (night mode) would be great

**Comment by aaronjwood** [comment]
@Artaud speaking of the timers, is 100ms a hard requirement? Wondering if we can dial back the interval to help with battery life. When I have been able to run sleep tracking all night in the past I found that it's a good 11-12% hit to my Fenix battery :(

**Comment by Artaud** [comment]
@aaronjwood The 100ms is in place mainly for the accelerometer, since we need to detect fairly quick movements during sleep. Most of the night there is nothing going on, but when it is, the movements tend to be quick - like a leg jerk.
I think we could conservatively move to 200ms and see where it takes us.

**Comment by DonStefano** [comment]
I found a workaround for this issue. Go to settings/system/lightning/during activity/gesture and switch it to off. Now the light does not switch on if you are running or cycling and turning your wrist, but that didn't work very well ether. Check that it's still on for buttons and alarms so it'll turn on if you need it during sport.

HTH Stefan

**Comment by aaronjwood** [comment]
@DonStefano nice, this is perfect! I never relied on the gesture-based lighting anyway...

**Comment by Artaud** [comment]
@DonStefano This is amazing! Big thanks for finding out as this was pretty confusing but now I can see the logic and why on some models it was an issue and on some not.
